"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-tr8_c6su#rs#qvi^7$o6d8cmi7*6_vn8m64-)$stjng&t$em=-'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# ALLOWED_HOSTS = []
DOMAIN = os.environ.get("BACKEND_DOMAIN", "example.com")

ALLOWED_HOSTS = [
    DOMAIN, 
    f"{DOMAIN}:8000", 
    f"{DOMAIN}:3000", 
    f"{DOMAIN}:4200",
    'localhost', 
    'localhost:8000', 
    'localhost:3000', 
    'localhost:4200', 
    '*']

CORS_ALLOWED_ORIGINS = [
    "http://localhost",
    "http://localhost:4200",
    "http://localhost:8000",
    "http://localhost:3030",
    "http://localhost:3000",
    "http://127.0.0.1",
    "http://127.0.0.1:4200",
    "http://127.0.0.1:8000",
    "http://127.0.0.1:3030",
    "http://127.0.0.1:3000",
]

# CORS_ALLOW_ALL_ORIGINS=True
# Application definition

INSTALLED_APPS = [
    # 'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',                
    'rest_framework.authtoken',   # installed later
    'django_filters',   # installed later
    'user_forms',
    'cms',
    # 'revolap',
]
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    # "django.middleware.locale.LocaleMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    # 'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    # 'default': {
    #     'ENGINE': 'django.db.backends.sqlite3',
    #     'NAME': BASE_DIR / 'db.sqlite3',
    # }
    "default": {
        "ENGINE": "django.db.backends.postgresql_psycopg2",
        "NAME": os.environ.get("BACKEND_POSTGRES_DB", "sobosite"),
        "USER": os.environ.get("BACKEND_POSTGRES_USER", "sobosite"),
        "PASSWORD": os.environ.get("BACKEND_POSTGRES_PASSWORD", "sobosite"),
        "HOST": os.environ.get("BACKEND_POSTGRES_HOST", "127.0.0.1"),
        "PORT": os.environ.get("BACKEND_POSTGRES_PORT", "5432"),
        "LC_COLLATE": "",
        "LC_CTYPE": "",
    }
}

AUTH_USER_MODEL = "user_forms.User"

# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

LANGUAGES = [
    ("en", "English"),
]



# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

REST_FRAMEWORK= {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        # 'rest_framework.authentication.BasicAuthentication'
        'rest_framework.authentication.TokenAuthentication'   # installed later
        # 'rest_framework.authentication.SessionAuthentication'
    ]
}


MAILER_PORT = os.environ.get("SOBOSITE_MAILER_PORT", 465)
MAILER_HOST = os.environ.get("SOBOSITE_MAILER_HOST", "")
MAILER_USER  = os.environ.get("SOBOSITE_MAILER_USER", "")
MAILER_EMAIL_FROM  = os.environ.get("SOBOSITE_MAILER_EMAIL_FROM", "")
MAILER_PASSWORD  = os.environ.get("SOBOSITE_MAILER_PASSWORD", "")
