"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

import os
from pathlib import Path

VERSION = "0.0.3"

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-tr8_c6su#rs#qvi^7$o6d8cmi7*6_vn8m64-)$stjng&t$em=-'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# ALLOWED_HOSTS = []
DOMAIN = os.environ.get("BACKEND_DOMAIN", "example.com")

x_allowed_hosts_backend = [DOMAIN, 'krzysztofsobolewski.info', 'localhost', '127.0.0.1', '192.168.1.177']
x_allowed_ports_backend = [80, 8000,9000, 3000]

x_allowed_origins_frontend = ['localhost', '127.0.0.1', 'krzysztofsobolewski.info']
x_allowed_ports_frontend_cors = [80, 4200, 4400, 3030,3000]



ALLOWED_HOSTS = []
CORS_ALLOWED_ORIGINS = []

protocols = ['http://', 'https://']

for host in x_allowed_hosts_backend:
    ALLOWED_HOSTS.append(host)
    for protocol in protocols:
        ALLOWED_HOSTS.append(f"{protocol}{host}")
        for port in x_allowed_ports_backend:
            ALLOWED_HOSTS.append(f"{protocol}{host}:{port}")

for origin in x_allowed_origins_frontend:
    CORS_ALLOWED_ORIGINS.append(origin)
    for protocol in protocols:
        CORS_ALLOWED_ORIGINS.append(f"{protocol}{origin}")
        for port in x_allowed_ports_frontend_cors:
            CORS_ALLOWED_ORIGINS.append(f"{protocol}{origin}:{port}")


# ALLOWED_HOSTS = ['example.com', 'example.com:80', 'example.com:8000', 'example.com:9000', 'example.com:3000', 'krzysztofsobolewski.info', 'krzysztofsobolewski.info:80', 'krzysztofsobolewski.info:8000', 'krzysztofsobolewski.info:9000', 'krzysztofsobolewski.info:3000', 'localhost', 'localhost:80', 'localhost:8000', 'localhost:9000', 'localhost:3000', '127.0.0.1', '127.0.0.1:80', '127.0.0.1:8000', '127.0.0.1:9000', '127.0.0.1:3000']
# CORS_ALLOWED_ORIGINS =  ['localhost', 'localhost:80', 'localhost:4200', 'localhost:4400', 'localhost:3030', 'localhost:3000', '127.0.0.1', '127.0.0.1:80', '127.0.0.1:4200', '127.0.0.1:4400', '127.0.0.1:3030', '127.0.0.1:3000', 'krzysztofsobolewski.info', 'krzysztofsobolewski.info:80', 'krzysztofsobolewski.info:4200', 'krzysztofsobolewski.info:4400', 'krzysztofsobolewski.info:3030', 'krzysztofsobolewski.info:3000']



print("\n\nALLOWED_HOSTS ", ALLOWED_HOSTS)
print("\n\nCORS_ALLOWED_ORIGINS ", CORS_ALLOWED_ORIGINS)

# CORS_ALLOW_ALL_ORIGINS=True
# Application definition

INSTALLED_APPS = [
    # 'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',                
    'rest_framework.authtoken',   # installed later
    'django_filters',   # installed later
    'user_forms',
    'cms',
    # 'revolap',
]
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    # "django.middleware.locale.LocaleMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    # 'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    # 'default': {
    #     'ENGINE': 'django.db.backends.sqlite3',
    #     'NAME': BASE_DIR / 'db.sqlite3',
    # }
    "default": {
        "ENGINE": "django.db.backends.postgresql_psycopg2",
        "NAME": os.environ.get("BACKEND_POSTGRES_DB", "sobosite"),
        "USER": os.environ.get("BACKEND_POSTGRES_USER", "sobosite"),
        "PASSWORD": os.environ.get("BACKEND_POSTGRES_PASSWORD", "sobosite"),
        "HOST": os.environ.get("BACKEND_POSTGRES_HOST", "127.0.0.1"),
        "PORT": os.environ.get("BACKEND_POSTGRES_PORT", "5432"),
        "LC_COLLATE": "",
        "LC_CTYPE": "",
    }
}

AUTH_USER_MODEL = "user_forms.User"

# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

LANGUAGES = [
    ("en", "English"),
]



# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

REST_FRAMEWORK= {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        # 'rest_framework.authentication.BasicAuthentication'
        'rest_framework.authentication.TokenAuthentication'   # installed later
        # 'rest_framework.authentication.SessionAuthentication'
    ]
}


MAILER_PORT = os.environ.get("SOBOSITE_MAILER_PORT", 465)
MAILER_HOST = os.environ.get("SOBOSITE_MAILER_HOST", "")
MAILER_USER  = os.environ.get("SOBOSITE_MAILER_USER", "")
MAILER_EMAIL_FROM  = os.environ.get("SOBOSITE_MAILER_EMAIL_FROM", "")
MAILER_PASSWORD  = os.environ.get("SOBOSITE_MAILER_PASSWORD", "")
