# Generated by Django 5.0.6 on 2024-08-05 23:30

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DimOrigin',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(max_length=255)),
                ('code_name', models.CharField(max_length=50)),
                ('desc', models.CharField(max_length=255, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('is_visible', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DimEntity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(max_length=255)),
                ('code_name', models.CharField(max_length=50)),
                ('desc', models.CharField(max_length=255, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('is_visible', models.BooleanField(default=False)),
                ('region', models.CharField(max_length=50)),
                ('addr_city', models.CharField(max_length=255)),
                ('addr_province', models.CharField(max_length=255, null=True)),
                ('addr_country', models.CharField(max_length=10)),
                ('unit_account_prefix', models.CharField(max_length=50, null=True)),
                ('addr_details', models.CharField(max_length=255)),
                ('addr_postal_code', models.CharField(max_length=50, null=True)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='revolap.dimentity')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DimAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(max_length=255)),
                ('code_name', models.CharField(max_length=50)),
                ('desc', models.CharField(max_length=255, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('is_visible', models.BooleanField(default=False)),
                ('account_no', models.CharField(max_length=255, null=True)),
                ('account_no_range_bottom', models.IntegerField(default=0, null=True)),
                ('account_no_range_top', models.IntegerField(default=0, null=True)),
                ('is_account_type', models.BooleanField(default=False)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='revolap.dimaccount')),
                ('entity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='revolap.dimentity')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DimProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(max_length=255)),
                ('code_name', models.CharField(max_length=50)),
                ('desc', models.CharField(max_length=255, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('is_visible', models.BooleanField(default=False)),
                ('sku', models.CharField(max_length=255, null=True)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='revolap.dimproduct')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DimScenario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(max_length=255)),
                ('code_name', models.CharField(max_length=50)),
                ('desc', models.CharField(max_length=255, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('is_visible', models.BooleanField(default=False)),
                ('scenario_type', models.CharField(max_length=255)),
                ('scenario_period_start', models.CharField(max_length=255, null=True)),
                ('scenario_period_end', models.CharField(max_length=255, null=True)),
                ('scenario_time_data', models.JSONField()),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='revolap.dimscenario')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DimTime',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(max_length=255)),
                ('code_name', models.CharField(max_length=50)),
                ('desc', models.CharField(max_length=255, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('is_visible', models.BooleanField(default=False)),
                ('period_type', models.CharField(default='month')),
                ('dt_start', models.DateTimeField(auto_now=True, db_index=True)),
                ('dt_end', models.DateTimeField(auto_now=True, db_index=True)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='revolap.dimtime')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(max_length=255)),
                ('code_name', models.CharField(max_length=50)),
                ('desc', models.CharField(max_length=255, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('is_visible', models.BooleanField(default=False)),
                ('unit_type', models.CharField(max_length=30)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='revolap.measurement')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RevOlapCubeDef',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(max_length=255)),
                ('code_name', models.CharField(max_length=50)),
                ('desc', models.CharField(max_length=255, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('is_visible', models.BooleanField(default=False)),
                ('dimensions', models.JSONField()),
                ('fact_entity', models.CharField(max_length=255, null=True)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='revolap.revolapcubedef')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
