# Generated by Django 5.0.6 on 2024-08-05 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revolap', '0002_remove_dimentity_addr_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dimentity',
            name='addr_country_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
