# Generated by Django 5.0.6 on 2024-08-06 20:57

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revolap', '0004_alter_dimscenario_scenario_time_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='RevOlapCubeFact_CubeTest1',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('num_value', models.DecimalField(decimal_places=10, default=0.0, max_digits=20)),
                ('num_value_agg_tmp', models.DecimalField(decimal_places=10, default=0.0, max_digits=20)),
                ('num_value_agg', models.DecimalField(decimal_places=10, default=0.0, max_digits=20)),
                ('num_value_conso_tmp', models.DecimalField(decimal_places=10, default=0.0, max_digits=20)),
                ('num_value_conso', models.DecimalField(decimal_places=10, default=0.0, max_digits=20)),
                ('is_dirty_value', models.BooleanField(default=False)),
                ('is_dirty_agg', models.BooleanField(default=False)),
                ('is_dirty_conso', models.BooleanField(default=False)),
                ('value_updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('agg_updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('agg_tmp_updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('conso_updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('conso_tmp_updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='revolap.dimaccount')),
                ('entity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='revolap.dimentity')),
                ('measurement', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='revolap.measurement')),
                ('origin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='revolap.dimorigin')),
                ('parent_fact', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='revolap.revolapcubefact_cubetest1')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='revolap.dimproduct')),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='revolap.dimscenario')),
                ('time', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='revolap.dimtime')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
