# Generated by Django 4.2.20 on 2025-03-26 23:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CmsCntTrunkId',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('published_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_visible', models.BooleanField(default=False)),
                ('main_category', models.CharField(max_length=500)),
                ('all_categories', models.CharField(max_length=2500)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CmsContentBranchTypeNewsPost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('lang', models.CharField(max_length=10)),
                ('published_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_visible', models.BooleanField(default=False)),
                ('category', models.CharField(max_length=500, null=True)),
                ('title', models.CharField()),
                ('desc', models.CharField(null=True)),
                ('news_source', models.CharField()),
                ('trunk', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cms.CmsCntTrunkId')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CmsContentBranchTypeBlogPost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('lang', models.CharField(max_length=10)),
                ('published_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_visible', models.BooleanField(default=False)),
                ('category', models.CharField(max_length=500, null=True)),
                ('title', models.CharField()),
                ('desc', models.CharField(null=True)),
                ('trunk', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cms.CmsCntTrunkId')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
