# Generated by Django 5.0.6 on 2024-07-11 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_forms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password_reset_token',
            field=models.CharField(max_length=600, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='register_activation_token',
            field=models.CharField(max_length=600, null=True, unique=True),
        ),
    ]
