# Generated by Django 5.2.1 on 2025-06-13 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_forms', '0003_alter_user_first_name_alter_user_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
    ]
